init:
- SET PATH=C:\Program Files\OpenSSL;C:\Tools\php;%PATH%
- SET COMPOSER_NO_INTERACTION=1
# - SET PHP=1 # This var is connected to PHP install cache
- SET ANSICON=121x90 (121x90)
install: 
- choco search php --exact --all-versions -r

# - cinst --params '""/InstallDir:C:\Tools\php""' php # Latest 7.2
# - cinst --params '""/InstallDir:C:\Tools\php""' php --version 7.1.12 # Does not install correctly?
# - cinst --params '""/InstallDir:C:\Tools\php""' php --version 7.0.26 # Does not install correctly!
- cinst --params '""/InstallDir:C:\Tools\php""' php --version 5.6.32
# - cinst --params '""/InstallDir:C:\Tools\php""' php --version 5.5.38
# - cinst --params '""/InstallDir:C:\Tools\php""' php --version 5.4.45

- php.exe --ini
- echo extension_dir = "ext" >> C:\Tools\php\php.ini
# Recent syntax
# - echo extension=mbstring >> C:\Tools\php\php.ini
# - echo extension=openssl >> C:\Tools\php\php.ini
# Old syntax
- echo extension=php_mbstring.dll >> C:\Tools\php\php.ini
- echo extension=php_openssl.dll >> C:\Tools\php\php.ini
# - refreshenv
# Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
# appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
# 'appveyor-retry' is not recognized as an internal or external command, operable program or batch file.
- dir C:\Tools\php
- dir C:\Tools\php\ext
# - appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar

# - php.exe -r "copy('https://getcomposer.org/Composer-Setup.exe', 'Composer-Setup.exe');"
# - Composer-Setup.exe # Needs graphical display window

- php.exe -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
# - php.exe -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
- php.exe composer-setup.php
- php.exe -r "unlink('composer-setup.php');"

# - echo @php %%~dp0composer.phar %%* > composer.bat
- php.exe composer.phar
# - composer
- php.exe composer.phar --working-dir=scripts update
- php.exe scripts/install-manager.php --ansi
- php.exe scripts/install-manager.php -vvv --ansi -- failsafe php.exe composer.phar global require --dev phpstan/phpstan-phpunit
- php.exe scripts/install-manager.php -vvv --ansi -- run php.exe composer.phar global require --dev phpunit/phpunit
# - php.exe composer.phar require --dev phpstan/phpstan-phpunit
- dir
- dir *.php
- dir "%HOMEDRIVE%%HOMEPATH%" # Directory of C:\Users\appveyor
- dir "%HOMEDRIVE%%HOMEPATH%\AppData\Roaming\Composer" # Directory of C:\Users\appveyor\AppData\Roaming\Composer
# - dir "%HOMEDRIVE%%HOMEPATH%\AppData\Roaming\Composer\vendor\phpstan\phpstan\bin"
- php.exe composer.phar update
build: off
test_script:
# - vendor/bin/phpunit
# - php.exe "%HOMEDRIVE%%HOMEPATH%\AppData\Roaming\Composer\vendor\phpstan\phpstan\bin\phpstan" analyse -v --level max *.php tests
- php.exe scripts/install-manager.php -vvv --ansi -- orsuccess 127 php.exe "%HOMEDRIVE%%HOMEPATH%\AppData\Roaming\Composer\vendor\phpstan\phpstan\bin\phpstan" analyse --ansi --debug --level max --autoload-file=scripts/vendor/autoload.php scripts/lib
# 1 analyse fails
# *.php tests scripts\*.php 
