init:
- SET PATH=C:\Program Files\OpenSSL;C:\tools\php72;%PATH%
# c:\tools\php;
- SET COMPOSER_NO_INTERACTION=1
- SET PHP=1 # This var is connected to PHP install cache
- SET ANSICON=121x90 (121x90)
install: 
- cinst php
- echo extension=php_openssl.dll >> php.ini
# - refreshenv
# Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
# appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
# 'appveyor-retry' is not recognized as an internal or external command, operable program or batch file.
- dir c:\Tools
# tools\php
- appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
# - echo @php %%~dp0composer.phar %%* > composer.bat
- php.exe composer.phar
# - composer
- php.exe composer.phar --working-dir=scripts update
