init:
- SET PATH=C:\Program Files\OpenSSL;C:\Tools\php72;%PATH%
# c:\tools\php;
- SET COMPOSER_NO_INTERACTION=1
- SET PHP=1 # This var is connected to PHP install cache
- SET ANSICON=121x90 (121x90)
install: 
- cinst php
- php.exe --ini
- echo extension_dir = "ext" >> C:\Tools\php72\php.ini
- echo extension=openssl >> C:\Tools\php72\php.ini
# - echo extension_dir = "ext" >> php.ini
# - echo extension=openssl >> php.ini
# - php.exe --ini -c php.ini 
# - refreshenv
# Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
# appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
# 'appveyor-retry' is not recognized as an internal or external command, operable program or batch file.
- dir C:\Tools\php72
- dir C:\Tools\php72\ext
- appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
# - echo @php %%~dp0composer.phar %%* > composer.bat
- php.exe composer.phar
# - composer
- php.exe composer.phar --working-dir=scripts update # --disable-tls=true
# - php.exe -c php.ini composer.phar --working-dir=scripts update # --disable-tls=true
