checks:
    php:
        code_rating: true
        duplication: true
build:
    tests:
        override:
            -
                command: 'wget https://phar.phpunit.de/phpunit.phar --output-document=./phpunit; php phpunit --colors=always  --coverage-text --coverage-clover /tmp/coverage.xml'
                coverage:
                    file: '/tmp/coverage.xml'
                    format: 'clover'
